/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.HospitalEnterprise;
import model.Network.Network;
import model.Organization.MedicalCare;
import model.Organization.Organization;
import model.Person.Patients;
import model.Users.Users;
import model.WorkQueue.DiagnosticsWorkRequest;

/**
 *
 * @author sahithigaddam
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestLabTestJPanel
     */
    private JPanel usersPanel;
    private Enterprise enterprise;
    private Users userAccount;
    private Patients patientAccount;
    private MedicalCare organization;
    EcoSystem ecosystem;
    Network network;
    
    public RequestLabTestJPanel(JPanel usersPanel, Users account, Patients patientAccount, Enterprise enterprise,MedicalCare organization, EcoSystem ecosystem, Network network) {
        initComponents();
        
        this.usersPanel = usersPanel;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patientAccount=patientAccount;
        this.organization=organization;
        this.ecosystem=ecosystem;
        this.network=network;
         btnRequest.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequest = new javax.swing.JButton();
        tfComments = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTest1 = new javax.swing.JLabel();
        chkAntibodies = new javax.swing.JCheckBox();
        chkBloodType = new javax.swing.JCheckBox();
        chkSurvivalCapability = new javax.swing.JCheckBox();
        tfTest1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTests = new javax.swing.JLabel();
        chkWbcCount = new javax.swing.JCheckBox();
        lblTest2 = new javax.swing.JLabel();
        tfTest2 = new javax.swing.JTextField();
        lblTest3 = new javax.swing.JLabel();
        tfTest3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        btnRequest.setBackground(new java.awt.Color(0, 183, 210));
        btnRequest.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest.setText("Request Tests");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        tfComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCommentsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 183, 210));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTest1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTest1.setText("Additional test");

        chkAntibodies.setBackground(new java.awt.Color(0, 183, 210));
        chkAntibodies.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkAntibodies.setForeground(new java.awt.Color(255, 255, 255));
        chkAntibodies.setText("Reactive Antibodies ");
        chkAntibodies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntibodiesActionPerformed(evt);
            }
        });

        chkBloodType.setBackground(new java.awt.Color(0, 183, 210));
        chkBloodType.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkBloodType.setForeground(new java.awt.Color(255, 255, 255));
        chkBloodType.setText("Blood Type");

        chkSurvivalCapability.setBackground(new java.awt.Color(0, 183, 210));
        chkSurvivalCapability.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkSurvivalCapability.setForeground(new java.awt.Color(255, 255, 255));
        chkSurvivalCapability.setText("Survival Capability");

        tfTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTest1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Comments*");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 183, 210));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REQUEST TEST ");

        lblTests.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTests.setForeground(new java.awt.Color(0, 183, 210));
        lblTests.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTests.setText("Frequent Tests Conducted");

        chkWbcCount.setBackground(new java.awt.Color(0, 183, 210));
        chkWbcCount.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkWbcCount.setForeground(new java.awt.Color(255, 255, 255));
        chkWbcCount.setText("WBC Count");
        chkWbcCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWbcCountActionPerformed(evt);
            }
        });

        lblTest2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTest2.setText("Additional test");

        tfTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTest2ActionPerformed(evt);
            }
        });

        lblTest3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTest3.setText("Additional test");

        tfTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTest3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RequestLab/bloodType.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RequestLab/survivalCapability1.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RequestLab/reactiveAntibodies.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RequestLab/wbc.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(chkWbcCount)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(chkAntibodies))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(chkBloodType)
                                                    .addGap(227, 227, 227))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(195, 195, 195)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(chkSurvivalCapability, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(42, 42, 42))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTests, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 415, Short.MAX_VALUE)))
                        .addGap(160, 160, 160))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfComments, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(721, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTests)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBloodType)
                    .addComponent(chkSurvivalCapability))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkWbcCount)
                    .addComponent(chkAntibodies))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest1)
                    .addComponent(tfTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest2)
                    .addComponent(tfTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest3)
                    .addComponent(tfTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRequest)
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(btnBack)
                    .addContainerGap(971, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed

        String message = tfComments.getText();
        int f=0;

        DiagnosticsWorkRequest request = new DiagnosticsWorkRequest();
        request.setPatient(patientAccount);

        if(message==null||message.equals("")){
            JOptionPane.showMessageDialog(null, "Wait ! Please fill the comments field");

            return;
        }
        request.setMessage(message);

        if(chkBloodType.isSelected()){
            f=1;
            request.getTests().add("Blood Typing");
        }
        if(chkSurvivalCapability.isSelected()){
            f=1;
            request.getTests().add("Survival Capability");
        }
        if(chkAntibodies.isSelected()){
            f=1;
            request.getTests().add("Reactive Antibodies");
        }
        if(chkWbcCount.isSelected()){
            f=1;
            request.getTests().add("WBC Count");
        }
        if(!tfTest1.getText().isEmpty()){
            f=1;
            request.getTests().add(tfTest1.getText());
        }
        if(!tfTest2.getText().isEmpty()){
            f=1;
            request.getTests().add(tfTest2.getText());
        }if(!tfTest3.getText().isEmpty()){
            f=1;
            request.getTests().add(tfTest3.getText());
        }

        boolean check;
        check=f>0;
        if(!check){
            JOptionPane.showMessageDialog(null,"Please selects testes to perform");
            return;
        }

        request.setSender(userAccount);
        request.setStatus("Sent");

        Organization org = null;
        Enterprise e=null;

        for(Enterprise ent: network.getListOfEnterprises().getEnterpriseList()){
            if(ent instanceof HospitalEnterprise&&ent.getOrganizationName().equalsIgnoreCase(enterprise.getOrganizationName())){
                e=ent;
                ent.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        }

        if(f==0){
            JOptionPane.showMessageDialog(null, "Please fill the details");
        }else{
            JOptionPane.showMessageDialog(null, "Test requested");
            patientAccount.setIsAlive(false);// to not repeat patient
            btnRequest.setEnabled(false);}

        DoctorJPanel backbtn=new DoctorJPanel(usersPanel,userAccount,organization,enterprise,ecosystem,network);
        usersPanel.add("Customer Adding",backbtn);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);

    }//GEN-LAST:event_btnRequestActionPerformed

    private void tfCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCommentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        DoctorJPanel backbtn =new DoctorJPanel(usersPanel,userAccount,organization,enterprise,ecosystem,network);
        usersPanel.add("Customer Adding",backbtn);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);

    }//GEN-LAST:event_btnBackActionPerformed

    private void chkAntibodiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntibodiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntibodiesActionPerformed

    private void tfTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTest1ActionPerformed

    private void chkWbcCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWbcCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWbcCountActionPerformed

    private void tfTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTest2ActionPerformed

    private void tfTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTest3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTest3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JCheckBox chkAntibodies;
    private javax.swing.JCheckBox chkBloodType;
    private javax.swing.JCheckBox chkSurvivalCapability;
    private javax.swing.JCheckBox chkWbcCount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JLabel lblTests;
    private javax.swing.JTextField tfComments;
    private javax.swing.JTextField tfTest1;
    private javax.swing.JTextField tfTest2;
    private javax.swing.JTextField tfTest3;
    // End of variables declaration//GEN-END:variables
}
