/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.HospitalEnterprise;
import model.Network.Network;
import model.Organization.MedicalCare;
import model.Organization.Organization;
import model.Person.Patients;
import model.Users.Users;
import model.WorkQueue.DiagnosticsWorkRequest;

/**
 *
 * @author sahithigaddam
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestLabTestJPanel
     */
    private JPanel usersPanel;
    private Enterprise enterprise;
    private Users userAccount;
    private Patients patientAccount;
    private MedicalCare organization;
    EcoSystem ecosystem;
    Network network;
    
    public RequestLabTestJPanel(JPanel usersPanel, Users account, Patients patientAccount, Enterprise enterprise,MedicalCare organization, EcoSystem ecosystem, Network network) {
        initComponents();
        
        this.usersPanel = usersPanel;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patientAccount=patientAccount;
        this.organization=organization;
        this.ecosystem=ecosystem;
        this.network=network;
         btnRequest.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequest = new javax.swing.JButton();
        tfComments = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTest1 = new javax.swing.JLabel();
        chkAntibodies = new javax.swing.JCheckBox();
        chkBloodType = new javax.swing.JCheckBox();
        chkSurvivalCapability = new javax.swing.JCheckBox();
        tfTest1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTests = new javax.swing.JLabel();
        chkWbcCount = new javax.swing.JCheckBox();
        lblTest2 = new javax.swing.JLabel();
        tfTest2 = new javax.swing.JTextField();
        lblTest3 = new javax.swing.JLabel();
        tfTest3 = new javax.swing.JTextField();

        btnRequest.setBackground(new java.awt.Color(255, 0, 51));
        btnRequest.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnRequest.setText("Request Tests");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        tfComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCommentsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTest1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTest1.setText("Additional test");

        chkAntibodies.setBackground(new java.awt.Color(255, 255, 255));
        chkAntibodies.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkAntibodies.setText("Reactive Antibodies ");
        chkAntibodies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntibodiesActionPerformed(evt);
            }
        });

        chkBloodType.setBackground(new java.awt.Color(255, 255, 255));
        chkBloodType.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkBloodType.setText("Blood Type");

        chkSurvivalCapability.setBackground(new java.awt.Color(255, 255, 255));
        chkSurvivalCapability.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkSurvivalCapability.setText("Survival Capability");

        tfTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTest1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Comments:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REQUEST TEST ");

        lblTests.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblTests.setForeground(new java.awt.Color(255, 0, 51));
        lblTests.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTests.setText("Frequent Tests Conducted");

        chkWbcCount.setBackground(new java.awt.Color(255, 255, 255));
        chkWbcCount.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        chkWbcCount.setText("WBC Count");
        chkWbcCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkWbcCountActionPerformed(evt);
            }
        });

        lblTest2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTest2.setText("Additional test");

        tfTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTest2ActionPerformed(evt);
            }
        });

        lblTest3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTest3.setText("Additional test");

        tfTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTest3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(chkWbcCount)
                .addGap(115, 115, 115)
                .addComponent(chkAntibodies)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(chkBloodType)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(202, 202, 202)
                                    .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfComments, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lblTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tfTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(chkSurvivalCapability, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(114, 114, 114)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(315, 315, 315)
                            .addComponent(lblTests, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(158, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkWbcCount)
                    .addComponent(chkAntibodies))
                .addGap(287, 287, 287))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTests)))
                    .addGap(107, 107, 107)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkSurvivalCapability)
                        .addComponent(chkBloodType))
                    .addGap(161, 161, 161)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTest1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTest2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTest3))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addComponent(btnRequest)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed

        String message = tfComments.getText();
        int f=0;

        DiagnosticsWorkRequest request = new DiagnosticsWorkRequest();
        request.setPatient(patientAccount);

        if(message==null||message.equals("")){
            JOptionPane.showMessageDialog(null, "Wait ! Please fill the comments field");

            return;
        }
        request.setMessage(message);

        if(chkBloodType.isSelected()){
            f=1;
            request.getTests().add("Blood Typing");
        }
        if(chkSurvivalCapability.isSelected()){
            f=1;
            request.getTests().add("Survival Capability");
        }
        if(chkAntibodies.isSelected()){
            f=1;
            request.getTests().add("Reactive Antibodies");
        }
        if(chkWbcCount.isSelected()){
            f=1;
            request.getTests().add("WBC Count");
        }
        if(!tfTest1.getText().isEmpty()){
            f=1;
            request.getTests().add(tfTest1.getText());
        }
        if(!tfTest2.getText().isEmpty()){
            f=1;
            request.getTests().add(tfTest2.getText());
        }if(!tfTest3.getText().isEmpty()){
            f=1;
            request.getTests().add(tfTest3.getText());
        }

        boolean check;
        check=f>0;
        if(!check){
            JOptionPane.showMessageDialog(null,"Please selects testes to perform");
            return;
        }

        request.setSender(userAccount);
        request.setStatus("Sent");

        Organization org = null;
        Enterprise e=null;

        for(Enterprise ent: network.getListOfEnterprises().getEnterpriseList()){
            if(ent instanceof HospitalEnterprise&&ent.getOrganizationName().equalsIgnoreCase(enterprise.getOrganizationName())){
                e=ent;
                ent.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        }

        if(f==0){
            JOptionPane.showMessageDialog(null, "Please fill the details");
        }else{
            JOptionPane.showMessageDialog(null, "Test requested");
            patientAccount.setIsAlive(false);// to not repeat patient
            btnRequest.setEnabled(false);}

        DoctorJPanel backbtn=new DoctorJPanel(usersPanel,userAccount,organization,enterprise,ecosystem,network);
        usersPanel.add("Customer Adding",backbtn);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);

    }//GEN-LAST:event_btnRequestActionPerformed

    private void tfCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCommentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        DoctorJPanel backbtn =new DoctorJPanel(usersPanel,userAccount,organization,enterprise,ecosystem,network);
        usersPanel.add("Customer Adding",backbtn);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);

    }//GEN-LAST:event_btnBackActionPerformed

    private void chkAntibodiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntibodiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntibodiesActionPerformed

    private void tfTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTest1ActionPerformed

    private void chkWbcCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWbcCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWbcCountActionPerformed

    private void tfTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTest2ActionPerformed

    private void tfTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTest3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTest3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JCheckBox chkAntibodies;
    private javax.swing.JCheckBox chkBloodType;
    private javax.swing.JCheckBox chkSurvivalCapability;
    private javax.swing.JCheckBox chkWbcCount;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JLabel lblTests;
    private javax.swing.JTextField tfComments;
    private javax.swing.JTextField tfTest1;
    private javax.swing.JTextField tfTest2;
    private javax.swing.JTextField tfTest3;
    // End of variables declaration//GEN-END:variables
}
