/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.RehabEnterprise;
import model.Network.Network;
import model.Organization.MedicalCare;
import model.Organization.Organization;
import model.Person.Patients;
import model.Users.Users;
import model.WorkQueue.PhysicianWorkRequest;

/**
 *
 * @author sahithigaddam
 */
public class RequestTherapyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestTherapyJPanel
     */
    JPanel usersPanel;
    Users userAccount;
    String id;
    MedicalCare org;
    EcoSystem ecoSystem;
    Enterprise enterprise;
    Network network;
    Patients p;
    public RequestTherapyJPanel(JPanel usersPanel, MedicalCare organization, Users userAccount, Patients p, EcoSystem ecosystem, Enterprise enterprise, Network network) {
        initComponents();
        this.usersPanel=usersPanel;
        this.userAccount=userAccount;
        this.id=""+p.getPatientId();
        this.ecoSystem=ecosystem;
        this.p=p;
        this.org=organization;
        this.network=network;
        this.enterprise=enterprise;
        tfPatientId.setText(id);
        tfPatientName.setText(this.p.getPatientName());
        display();
    }
    
    public void display(){
        cbNetwork.addItem("--Select--");
        for(Network n: ecoSystem.getNetworkList()){
            cbNetwork.addItem(n.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientId = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        tfPatientId = new javax.swing.JTextField();
        tfPatientName = new javax.swing.JTextField();
        lblNetwork = new javax.swing.JLabel();
        cbNetwork = new javax.swing.JComboBox<>();
        lblTherapyCenter = new javax.swing.JLabel();
        lblTherapyCatalog = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        cbCenters = new javax.swing.JComboBox<>();
        cbTherapyCatalog = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        lblRequesTherapy = new javax.swing.JLabel();

        lblPatientId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPatientId.setForeground(new java.awt.Color(255, 0, 0));
        lblPatientId.setText("Patient ID:");

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(255, 0, 0));
        lblPatientName.setText("Patient Name:");

        tfPatientId.setEditable(false);

        tfPatientName.setEditable(false);

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNetwork.setForeground(new java.awt.Color(255, 0, 0));
        lblNetwork.setText("Network:");

        cbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNetworkActionPerformed(evt);
            }
        });

        lblTherapyCenter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTherapyCenter.setForeground(new java.awt.Color(255, 0, 0));
        lblTherapyCenter.setText("Therapy Centers:");

        lblTherapyCatalog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTherapyCatalog.setForeground(new java.awt.Color(255, 0, 0));
        lblTherapyCatalog.setText("Therapy Category:");

        btnSubmit.setBackground(new java.awt.Color(255, 0, 51));
        btnSubmit.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        cbCenters.setBackground(new java.awt.Color(255, 0, 51));
        cbCenters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        cbCenters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCentersActionPerformed(evt);
            }
        });

        cbTherapyCatalog.setBackground(new java.awt.Color(255, 0, 51));
        cbTherapyCatalog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        cbTherapyCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTherapyCatalogActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRequesTherapy.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblRequesTherapy.setForeground(new java.awt.Color(255, 0, 51));
        lblRequesTherapy.setText("Request Therapy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(lblRequesTherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTherapyCenter)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(231, 231, 231)
                                        .addComponent(lblPatientId))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(223, 223, 223)
                                        .addComponent(lblPatientName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(235, 235, 235)
                                        .addComponent(lblNetwork))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(lblTherapyCatalog)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTherapyCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCenters, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btnSubmit)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblRequesTherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTherapyCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCenters, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTherapyCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTherapyCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNetworkActionPerformed

        cbCenters.removeAllItems();
        cbCenters.addItem("--Select--");
        for(Network n: ecoSystem.getNetworkList()){
            if(cbNetwork.getSelectedItem().toString().equalsIgnoreCase(n.getName())){
                for(Enterprise e: n.getListOfEnterprises().getEnterpriseList()){
                    if(e.getenterpriseType().getType().equalsIgnoreCase("Physio")){
                        cbCenters.addItem(e.getOrganizationName());
                    }

                }
            }
        }
    }//GEN-LAST:event_cbNetworkActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        boolean check;
        check=(!(cbCenters.getSelectedItem()==null||cbNetwork.getSelectedItem()==null||cbTherapyCatalog.getSelectedItem()==null));

        if(!check){
            JOptionPane.showMessageDialog(null, "Select proper options (or) doctors not available");
            return;
        }

        PhysicianWorkRequest request = new PhysicianWorkRequest();
        request.setPatient(p);
        Organization orga = null;
        request.setSender(userAccount);
        request.setStatus("Requested");

        for(Network n: ecoSystem.getNetworkList()){
            if(n.getName().equalsIgnoreCase(cbNetwork.getSelectedItem().toString())){
                for(Enterprise e: n.getListOfEnterprises().getEnterpriseList()){
                    if(e instanceof RehabEnterprise&&e.getOrganizationName().equalsIgnoreCase(cbCenters.getSelectedItem().toString())){
                        for(Organization o:e.getLisOfOrganizations().getOrganizationList()){
                            if(o.getOrganizationName().equalsIgnoreCase(cbTherapyCatalog.getSelectedItem().toString())){
                                orga=o;
                                o.getWorkQueue().getWorkRequestList().add(request);
                                userAccount.getWorkQueue().getWorkRequestList().add(request);
                                JOptionPane.showMessageDialog(null, "Therapist service requested");
                            }
                        }
                    }
                }
            }
        }

        DoctorJPanel sa=new DoctorJPanel(usersPanel,userAccount,org,enterprise,ecoSystem,network);
        usersPanel.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbCentersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCentersActionPerformed

        cbTherapyCatalog.removeAllItems();
        for(Network n: ecoSystem.getNetworkList()){
            if(cbNetwork.getSelectedItem().toString().equalsIgnoreCase(n.getName())){
                for(Enterprise e: n.getListOfEnterprises().getEnterpriseList()){
                    if(e.getOrganizationName().equalsIgnoreCase(cbCenters.getSelectedItem().toString())){
                        for(Organization o: e.getLisOfOrganizations().getOrganizationList()){
                            cbTherapyCatalog.addItem(o.getOrganizationName());
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_cbCentersActionPerformed

    private void cbTherapyCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTherapyCatalogActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTherapyCatalogActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DoctorJPanel sa=new DoctorJPanel(usersPanel,userAccount,org,enterprise,ecoSystem,network);
        usersPanel.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbCenters;
    private javax.swing.JComboBox<String> cbNetwork;
    private javax.swing.JComboBox<String> cbTherapyCatalog;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRequesTherapy;
    private javax.swing.JLabel lblTherapyCatalog;
    private javax.swing.JLabel lblTherapyCenter;
    private javax.swing.JTextField tfPatientId;
    private javax.swing.JTextField tfPatientName;
    // End of variables declaration//GEN-END:variables
}
