/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Network.Network;
import model.Organization.MedicalCare;
import model.Organization.Organization;
import model.Person.Patients;
import model.Users.Users;
import model.Waitlist.Waitlist;

/**
 *
 * @author sahithigaddam
 */
public class RequestBloodJpanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestBloodJpanel
     */
    
    JPanel usersPanel;
    Users userAccount;
    String id;
    Organization org;
    EcoSystem ecoSystem;
    Enterprise enterprise;
    Network network;
    Patients p;
    
    public RequestBloodJpanel(JPanel usersPanel, MedicalCare organization, Users userAccount, Patients p, EcoSystem ecosystem, Enterprise enterprise, Network network) {
        initComponents();
        
        this.usersPanel=usersPanel;
        this.userAccount=userAccount;
        this.id=""+p.getPatientId();
        this.ecoSystem=ecosystem;
        this.p=p;
        this.org=organization;
        this.network=network;
        this.enterprise=enterprise;
        tfPatientId.setText(id);
        tfPatientName.setText(this.p.getPatientName());
    }
    
    public int calculateScore(){
        int counter=0;
        int age=cbAgeGroup.getSelectedIndex();
        int ped=cdMarriageStatus.getSelectedIndex();
        int sur=cbSurvivalBenefit.getSelectedIndex();
        int urg=cbUrgency.getSelectedIndex();
        if(age==1){
            counter=counter+10;
        }else if(age==2){
            counter=counter+8;
        }else if(age==3){
            counter=counter+6;
        }else if(age==4){
            counter=counter+4;
        }else if(age==5){
            counter=counter+2;
        }
        
        if(sur==1){
            counter=counter+10;
        }else if(sur==2){
            counter=counter+8;
        }else if(sur==3){
            counter=counter+6;
        }else if(sur==4){
            counter=counter+4;
        }else if(sur==5){
            counter=counter+2;
        }
        
        if(ped==1){
            counter=counter+10;
        }else if(ped==2){
            counter=counter+0;
        }
        
        if(urg==1){
            counter=counter+10;
        }else if(ped==2){
            counter=counter+5;
        }
        
        
        return counter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPatientId = new javax.swing.JTextField();
        tfPatientName = new javax.swing.JTextField();
        cbRequestBlood = new javax.swing.JComboBox<>();
        cbAgeGroup = new javax.swing.JComboBox<>();
        cdMarriageStatus = new javax.swing.JComboBox<>();
        cbSurvivalBenefit = new javax.swing.JComboBox<>();
        cbUrgency = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(0, 183, 210));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 183, 210));
        jLabel1.setText("Blood Request");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Patient ID :");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("Patient Name :");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Required Blood Type :");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Age Group :");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Marital Status:");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setText("Survival Benefit :");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("Urgency :");

        cbRequestBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cbRequestBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRequestBloodActionPerformed(evt);
            }
        });

        cbAgeGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "0-20", "20-35", "35-50", "50-65", ">65" }));

        cdMarriageStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Yes", "No" }));

        cbSurvivalBenefit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "85-100", "60-85", "50-60", "30-50", "<30" }));

        cbUrgency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Critical", "Not Critical" }));

        btnSubmit.setBackground(new java.awt.Color(0, 183, 210));
        btnSubmit.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 183, 210));
        btnBack.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BloodRequest/blood-request.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(767, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnBack)
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(508, 508, 508)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(12, 12, 12)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfPatientId)
                        .addComponent(tfPatientName)
                        .addComponent(cbRequestBlood, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAgeGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdMarriageStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSurvivalBenefit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(533, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbRequestBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cdMarriageStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbSurvivalBenefit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(126, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean check;
        check=(cdMarriageStatus.getSelectedIndex()>0&&cbAgeGroup.getSelectedIndex()>0&&cbRequestBlood.getSelectedIndex()>0&&cbSurvivalBenefit.getSelectedIndex()>0&&cbUrgency.getSelectedIndex()>0);
        if(check == false) {
            JOptionPane.showMessageDialog(null, "Please provide all parameters");
            return;
        }

        int dup=0;
        for(Waitlist w: ecoSystem.getWaitList()){
            if(w.getPatient().getPatientId()==p.getPatientId()&&w.getBlood().equalsIgnoreCase(cbRequestBlood.getSelectedItem().toString())){
                dup++;
            }
        }

        check=(dup==0);
        if(!check){
            JOptionPane.showMessageDialog(null, "Patient is already in waitlist");
            return;
        }

        int score=0;
        if(ecoSystem.getWaitList().size()<1){
            score=calculateScore();
        }else{
            Collections.sort(ecoSystem.getWaitList());
            for(Waitlist w: ecoSystem.getWaitList()){
                if(w.getBlood().equalsIgnoreCase(cbRequestBlood.getSelectedItem().toString())){
                    score=w.getPatientWaitlist()-1;
                    break;
                }else{
                    score=calculateScore();
                }
            }

        }

        Waitlist waitlist_val=new Waitlist(p,cbAgeGroup.getSelectedItem().toString(),cdMarriageStatus.getSelectedItem().toString(),cbSurvivalBenefit.getSelectedItem().toString(),cbUrgency.getSelectedItem().toString(),cbRequestBlood.getSelectedItem().toString(),score,0);
        ecoSystem.addWaitlist(waitlist_val);

        DoctorJPanel doctorWorkArea=new DoctorJPanel(usersPanel, userAccount,(MedicalCare) org,enterprise,ecoSystem,network);
        doctorWorkArea.load_wait_table();
        usersPanel.add("Lab test",doctorWorkArea);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DoctorJPanel doctorWorkArea=new DoctorJPanel(usersPanel, userAccount,(MedicalCare) org,enterprise,ecoSystem,network);
        doctorWorkArea.load_wait_table();
        usersPanel.add("Lab test",doctorWorkArea);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbRequestBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRequestBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRequestBloodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbAgeGroup;
    private javax.swing.JComboBox<String> cbRequestBlood;
    private javax.swing.JComboBox<String> cbSurvivalBenefit;
    private javax.swing.JComboBox<String> cbUrgency;
    private javax.swing.JComboBox<String> cdMarriageStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfPatientId;
    private javax.swing.JTextField tfPatientName;
    // End of variables declaration//GEN-END:variables
}
