/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Enterprise.RehabEnterprise;
import model.Network.Network;
import model.Organization.MedicalCare;
import model.Organization.Organization;
import model.Person.Patients;
import model.Users.Users;
import model.WorkQueue.PhysicianWorkRequest;

/**
 *
 * @author sahithigaddam
 */
public class RequestTherapyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestTherapyJPanel
     */
    JPanel usersPanel;
    Users userAccount;
    String id;
    MedicalCare org;
    EcoSystem ecoSystem;
    Enterprise enterprise;
    Network network;
    Patients p;
    public RequestTherapyJPanel(JPanel usersPanel, MedicalCare organization, Users userAccount, Patients p, EcoSystem ecosystem, Enterprise enterprise, Network network) {
        initComponents();
        this.usersPanel=usersPanel;
        this.userAccount=userAccount;
        this.id=""+p.getPatientId();
        this.ecoSystem=ecosystem;
        this.p=p;
        this.org=organization;
        this.network=network;
        this.enterprise=enterprise;
        tfPatientId.setText(id);
        tfPatientName.setText(this.p.getPatientName());
        display();
    }
    
    public void display(){
        cbNetwork.addItem("--Select--");
        for(Network n: ecoSystem.getNetworkList()){
            cbNetwork.addItem(n.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientId = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        tfPatientId = new javax.swing.JTextField();
        tfPatientName = new javax.swing.JTextField();
        lblNetwork = new javax.swing.JLabel();
        cbNetwork = new javax.swing.JComboBox<>();
        lblTherapyCenter = new javax.swing.JLabel();
        lblTherapyCatalog = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        cbCenters = new javax.swing.JComboBox<>();
        cbTherapyCatalog = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        lblRequesTherapy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblPatientId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPatientId.setText("Patient ID:");

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPatientName.setText("Patient Name:");

        tfPatientId.setEditable(false);

        tfPatientName.setEditable(false);

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNetwork.setText("Network:");

        cbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNetworkActionPerformed(evt);
            }
        });

        lblTherapyCenter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTherapyCenter.setText("Therapy Centers:");

        lblTherapyCatalog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTherapyCatalog.setText("Therapy Category:");

        btnSubmit.setBackground(new java.awt.Color(0, 183, 210));
        btnSubmit.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        cbCenters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        cbCenters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCentersActionPerformed(evt);
            }
        });

        cbTherapyCatalog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        cbTherapyCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTherapyCatalogActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 183, 210));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblRequesTherapy.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblRequesTherapy.setForeground(new java.awt.Color(0, 183, 210));
        lblRequesTherapy.setText("Request Therapy");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RequestTherapy/requestTherapy1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnBack)
                        .addGap(311, 311, 311)
                        .addComponent(lblRequesTherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbTherapyCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(231, 231, 231)
                                                .addComponent(lblPatientId))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(223, 223, 223)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblNetwork)
                                                    .addComponent(lblPatientName)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTherapyCenter)
                                                    .addComponent(lblTherapyCatalog))))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbCenters, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRequesTherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCenters, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTherapyCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTherapyCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTherapyCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(btnSubmit))
                    .addComponent(jLabel1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNetworkActionPerformed

        cbCenters.removeAllItems();
        //cbCenters.addItem("--Select--");
        for(Network n: ecoSystem.getNetworkList()){
            if(cbNetwork.getSelectedItem().toString().equalsIgnoreCase(n.getName())){
                for(Enterprise e: n.getListOfEnterprises().getEnterpriseList()){
                    System.out.print("Enterprise Type******");
                    System.out.print(e.getenterpriseType().getType());
                    String type = e.getenterpriseType().toString();
                    if(type.equalsIgnoreCase("Rehabilitation Center")){
                        cbCenters.addItem(e.getOrganizationName());
                    }

                }
            }
        }
    }//GEN-LAST:event_cbNetworkActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        boolean check;
        check=(!(cbCenters.getSelectedItem()==null||cbNetwork.getSelectedItem()==null||cbTherapyCatalog.getSelectedItem()==null));

        if(!check){
            JOptionPane.showMessageDialog(null, "Select proper options (or) doctors not available");
            return;
        }

        PhysicianWorkRequest request = new PhysicianWorkRequest();
        request.setPatient(p);
        Organization orga = null;
        request.setSender(userAccount);
        request.setStatus("Requested");

        for(Network n: ecoSystem.getNetworkList()){
            if(n.getName().equalsIgnoreCase(cbNetwork.getSelectedItem().toString())){
                for(Enterprise e: n.getListOfEnterprises().getEnterpriseList()){
                    if(e instanceof RehabEnterprise&&e.getOrganizationName().equalsIgnoreCase(cbCenters.getSelectedItem().toString())){
                        for(Organization o:e.getLisOfOrganizations().getOrganizationList()){
                            if(o.getOrganizationName().equalsIgnoreCase(cbTherapyCatalog.getSelectedItem().toString())){
                                orga=o;
                                o.getWorkQueue().getWorkRequestList().add(request);
                                userAccount.getWorkQueue().getWorkRequestList().add(request);
                                JOptionPane.showMessageDialog(null, "Therapist service requested");
                            }
                        }
                    }
                }
            }
        }

        DoctorJPanel sa=new DoctorJPanel(usersPanel,userAccount,org,enterprise,ecoSystem,network);
        usersPanel.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbCentersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCentersActionPerformed

        cbTherapyCatalog.removeAllItems();
        for(Network n: ecoSystem.getNetworkList()){
            if(cbNetwork.getSelectedItem().toString().equalsIgnoreCase(n.getName())){
                for(Enterprise e: n.getListOfEnterprises().getEnterpriseList()){
                    if(e.getOrganizationName().equalsIgnoreCase(cbCenters.getSelectedItem().toString())){
                        for(Organization o: e.getLisOfOrganizations().getOrganizationList()){
                            cbTherapyCatalog.addItem(o.getOrganizationName());
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_cbCentersActionPerformed

    private void cbTherapyCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTherapyCatalogActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTherapyCatalogActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DoctorJPanel sa=new DoctorJPanel(usersPanel,userAccount,org,enterprise,ecoSystem,network);
        usersPanel.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbCenters;
    private javax.swing.JComboBox<String> cbNetwork;
    private javax.swing.JComboBox<String> cbTherapyCatalog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRequesTherapy;
    private javax.swing.JLabel lblTherapyCatalog;
    private javax.swing.JLabel lblTherapyCenter;
    private javax.swing.JTextField tfPatientId;
    private javax.swing.JTextField tfPatientName;
    // End of variables declaration//GEN-END:variables
}
