/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Network.Network;
import model.Organization.MedicalCare;
import model.Person.Patients;
import model.Users.Users;
import model.WorkQueue.DiagnosticsWorkRequest;

/**
 *
 * @author sahithigaddam
 */
public class TestDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestDataJPanel
     */
    
    JPanel usersPanel;
    
    Patients patient;
    String assist;
    EcoSystem ecosystem;
    Network network;
    Users userAccount;
    Enterprise enterprise;
    MedicalCare organization;
    String id;
    
    public TestDataJPanel(JPanel usersPanel, Users userAccount, String id,Patients patient,String assist,Enterprise enterprise,MedicalCare organization, EcoSystem ecosystem,Network network) {
        initComponents();
        
        
        this.id=id;
        this.patient=patient;
        this.assist=assist;
        this.userAccount=userAccount;
        this.usersPanel=usersPanel;
        this.enterprise=enterprise;
        this.ecosystem=ecosystem;
        this.network=network;
        this.organization=organization;
        taTestReport.setText(populatevalues());
    }
    
    public String populatevalues(){
        String test=" TEST RESULTS\n";
        test+="\nPatient ID : "+id+"\n";
        test+="\nPatient Name : "+patient.getPatientName()+"\n";
        test+="\nLab Assistant :"+assist+"\n";
        test+="**************************************************";
        
        
        for(int i=0;i<userAccount.getWorkQueue().getWorkRequestList().size();i++){
            if(userAccount.getWorkQueue().getWorkRequestList().get(i) instanceof DiagnosticsWorkRequest){
                if((""+((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getPatient().getPatientId()).equalsIgnoreCase(id)){
                    for(int j=0;j<((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getTests().size();j++){
                        test+="\n"+((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getTests().get(j) +" : "+((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getTestData().get(j)+"\n";
                    }
                }
            }
        
        }

    return test;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDone = new javax.swing.JButton();
        lblReport = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTestReport = new javax.swing.JTextArea();

        btnDone.setBackground(new java.awt.Color(0, 183, 210));
        btnDone.setForeground(new java.awt.Color(255, 255, 255));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lblReport.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lblReport.setForeground(new java.awt.Color(0, 183, 210));
        lblReport.setText("Test Report");

        taTestReport.setEditable(false);
        taTestReport.setBackground(new java.awt.Color(0, 200, 217));
        taTestReport.setColumns(20);
        taTestReport.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        taTestReport.setForeground(new java.awt.Color(255, 255, 255));
        taTestReport.setRows(5);
        jScrollPane1.setViewportView(taTestReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lblReport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnDone)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        DoctorJPanel satisfied_with_report=new DoctorJPanel(usersPanel,userAccount,organization,enterprise,ecosystem,network);
        usersPanel.add("Customer Adding",satisfied_with_report);
        CardLayout layout=(CardLayout)usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnDoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReport;
    private javax.swing.JTextArea taTestReport;
    // End of variables declaration//GEN-END:variables
}
