/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Donor;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Person.Donors;
import model.Person.DonorsDirectory;

/**
 *
 * @author varshareddykumbham
 */
public class DonorRegistrationJPanel extends javax.swing.JPanel {
    List<String> userList = new ArrayList<String>();
    String city;
    DB4OUtil dB4OUtil;
    DonorsDirectory donorDirectory;
    JPanel upContainer;
    String emailAdd;
    EcoSystem ecosystem;
    /**
     * Creates new form DonorRegistrationJPanel
     */
    public DonorRegistrationJPanel(JPanel upContainer, EcoSystem system, DonorsDirectory donorDirectory, DB4OUtil dB4OUtil) {
        initComponents();
        this.upContainer = upContainer;
        tfCity.setText(city);
        this.ecosystem = system;
        this.city = city;
        this.donorDirectory = donorDirectory;
        this.dB4OUtil = dB4OUtil;
        populateUser();
    }
    
    List<String> organList = new ArrayList<String>();

    public void populateUser() {
        for (Donors donor : ecosystem.getListOfDonors()) {
            userList.add(donor.getDonorName());
        }
    }
    private boolean checkAge(String age) {
        Pattern pattern = Pattern.compile("[0-9]+");
        Matcher matcher = pattern.matcher(age);
        boolean bool = matcher.matches();
        if (!bool) {
            JOptionPane.showMessageDialog(null, "Age should only be numbers");
            return false;
        } else {
            int age1 = Integer.parseInt(age);
            if (age1 < 0 || age1 > 200) {
                JOptionPane.showMessageDialog(null, "Age should between");
            }
            return true;
        }
    }

    public boolean checkFirstname(String text) {

        if (text.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")) {
            for (String s : userList) {
                if (s.equalsIgnoreCase(text)) {
                    JOptionPane.showMessageDialog(null, "User already exists");
                    return false;
                }
            }

            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Names should contain only alphabets");
            return false;
        }
    }

    private boolean checkPhone(String ph) {
        Pattern pattern = Pattern.compile("[0-9]{10}");
        Matcher matcher = pattern.matcher(ph);
        boolean bool = matcher.matches();
        if (!bool) {
            return true;
        } else {

            return true;
        }
    }

    private boolean checkUsernamePattern(String username) {
        int f = 0;

        Pattern pattern = Pattern.compile("(?!_).*[A-Za-z0-9._]+@[A-Za-z0-9._]+\\.[A-Za-z]{2,4}");
        Matcher matcher = pattern.matcher(username);
        boolean bool = matcher.matches();
        if (!bool) {
            JOptionPane.showMessageDialog(null, "Special characters are not allowed other than _, @");
            return false;
        } else {

            return true;
        }
    }

    boolean checkforunique() {
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        radSexMale = new javax.swing.JRadioButton();
        radSexFemale = new javax.swing.JRadioButton();
        lblBloodGroup = new javax.swing.JLabel();
        cbBloodGroup = new javax.swing.JComboBox();
        lblContact = new javax.swing.JLabel();
        tfContact = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        tfCity = new javax.swing.JTextField();
        lblOrganAvailable = new javax.swing.JLabel();
        radOrganAvailableNowYes = new javax.swing.JRadioButton();
        radOrganAvailableNo = new javax.swing.JRadioButton();
        lblPOCTitle = new javax.swing.JLabel();
        lblPOCName = new javax.swing.JLabel();
        tfPOCName = new javax.swing.JTextField();
        lblPOCContact = new javax.swing.JLabel();
        tfPOCContact = new javax.swing.JTextField();
        btnRegisterDonor = new javax.swing.JButton();

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("DONOR REGISTRATION FORM");

        tfName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 0, 51));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name:");

        lblAge.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 0, 51));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAge.setText("Age:");

        tfAge.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblSex.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSex.setForeground(new java.awt.Color(255, 0, 51));
        lblSex.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSex.setText("Sex:");

        radSexMale.setBackground(new java.awt.Color(255, 255, 255));
        radSexMale.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radSexMale.setText("Male");
        radSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexMaleActionPerformed(evt);
            }
        });

        radSexFemale.setBackground(new java.awt.Color(255, 255, 255));
        radSexFemale.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radSexFemale.setText("Female");
        radSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexFemaleActionPerformed(evt);
            }
        });

        lblBloodGroup.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblBloodGroup.setForeground(new java.awt.Color(255, 0, 51));
        lblBloodGroup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBloodGroup.setText("Blood Group:");

        cbBloodGroup.setBackground(new java.awt.Color(255, 0, 0));
        cbBloodGroup.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B+", "B-", "A+", "A-", "O+", "O-" }));
        cbBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloodGroupActionPerformed(evt);
            }
        });

        lblContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblContact.setForeground(new java.awt.Color(255, 0, 51));
        lblContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblContact.setText("Contact Number:");

        tfContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 0, 51));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email-Id:");

        tfEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblAddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 0, 51));
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddress.setText("Address:");

        tfAddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblCity.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 0, 51));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCity.setText("City:");

        tfCity.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblOrganAvailable.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblOrganAvailable.setForeground(new java.awt.Color(255, 0, 51));
        lblOrganAvailable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrganAvailable.setText("Is organ available now:");

        radOrganAvailableNowYes.setBackground(new java.awt.Color(255, 255, 255));
        radOrganAvailableNowYes.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radOrganAvailableNowYes.setText("Yes");

        radOrganAvailableNo.setBackground(new java.awt.Color(255, 255, 255));
        radOrganAvailableNo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radOrganAvailableNo.setText("No");

        lblPOCTitle.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        lblPOCTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblPOCTitle.setText("Point of contact in emergency:");

        lblPOCName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPOCName.setForeground(new java.awt.Color(255, 0, 51));
        lblPOCName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPOCName.setText("Name:");

        tfPOCName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblPOCContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPOCContact.setForeground(new java.awt.Color(255, 0, 51));
        lblPOCContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPOCContact.setText("Contact number:");

        tfPOCContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tfPOCContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOCContactActionPerformed(evt);
            }
        });

        btnRegisterDonor.setBackground(new java.awt.Color(255, 0, 51));
        btnRegisterDonor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnRegisterDonor.setText("Register As A Donor");
        btnRegisterDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDonorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPOCName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPOCContact))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfPOCName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfPOCContact, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblPOCTitle)
                                            .addGap(83, 83, 83))))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(radSexMale, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(radSexFemale))
                                                    .addComponent(cbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(tfCity, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(lblOrganAvailable)
                                        .addGap(18, 18, 18)
                                        .addComponent(radOrganAvailableNowYes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radOrganAvailableNo)))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegisterDonor)
                                .addGap(123, 123, 123))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(lblTitle))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAge))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSex)
                        .addComponent(radSexMale)
                        .addComponent(radSexFemale))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBloodGroup)
                        .addComponent(cbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContact)
                        .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddress)
                        .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCity))
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrganAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radOrganAvailableNowYes)
                        .addComponent(radOrganAvailableNo))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblPOCTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPOCName)
                        .addComponent(tfPOCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPOCContact)
                        .addComponent(tfPOCContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnRegisterDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        upContainer.remove(this);
        CardLayout layout = (CardLayout) upContainer.getLayout();
        layout.previous(upContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void radSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSexMaleActionPerformed

    private void radSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSexFemaleActionPerformed

    private void cbBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloodGroupActionPerformed

    private void tfPOCContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOCContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOCContactActionPerformed

    private void btnRegisterDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDonorActionPerformed

        int f = 0;
        String name = tfName.getText();
        //String lastname= txtName1.getText();
        String sex;
        emailAdd = tfEmail.getText();
        if (radSexMale.isSelected()) {
            sex = radSexMale.getText();
        } else {
            sex = radSexFemale.getText();
        }
        String bloodGroup = cbBloodGroup.getSelectedItem().toString();
        String contactNumber = tfContact.getText();
        String address = tfAddress.getText();
        String emergencyPOC = tfPOCName.getText();
        String emergencyPOC_Num = tfPOCContact.getText();
        int age = 30;

        boolean isOrganAvaiNow = false;
        if (radOrganAvailableNowYes.isSelected()) {
            isOrganAvaiNow = true;
        } else if (radOrganAvailableNo.isSelected()) {
            isOrganAvaiNow = false;
        }

        if (checkFirstname(name)) {
            f++;
        } else {
            return;
        }
        if (checkAge(tfAge.getText())) {
            age = Integer.parseInt(tfAge.getText());
            f++;
        } else {
            return;
        }

        if(contactNumber == null || contactNumber.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Contact Number");
            return;
        }
        else{
            if(!contactNumber.matches("^(?=.*[0-9]).{10,10}")){
                JOptionPane.showMessageDialog(null, "Please enter valid Contact Number");
                return;
            }
        }

        if (checkUsernamePattern(emailAdd)) {
            f++;
        } else {
            return;
        }
        if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "Address cannot be empty");
            return;
        }
        if(emergencyPOC_Num == null || emergencyPOC_Num.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Contact Number");
            return;
        }
        else{
            if(!emergencyPOC_Num.matches("^(?=.*[0-9]).{10,10}")){
                JOptionPane.showMessageDialog(null, "Please enter valid Contact Number");
                return;
            }
        }

        if (checkFirstname(emergencyPOC)) {
            f++;
        } else {
            return;
        }

        Donors d = ecosystem.createDonor(name, age, sex, bloodGroup, contactNumber, address, emailAdd, emergencyPOC, emergencyPOC_Num, isOrganAvaiNow, organList);
        dB4OUtil.storeSystem(ecosystem);
        JOptionPane.showMessageDialog(null, "Thanks for donation");
        populateUser();
    }//GEN-LAST:event_btnRegisterDonorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterDonor;
    private javax.swing.JComboBox cbBloodGroup;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganAvailable;
    private javax.swing.JLabel lblPOCContact;
    private javax.swing.JLabel lblPOCName;
    private javax.swing.JLabel lblPOCTitle;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radOrganAvailableNo;
    private javax.swing.JRadioButton radOrganAvailableNowYes;
    private javax.swing.JRadioButton radSexFemale;
    private javax.swing.JRadioButton radSexMale;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfContact;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPOCContact;
    private javax.swing.JTextField tfPOCName;
    // End of variables declaration//GEN-END:variables
}
