/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Donor;

import com.db4o.cs.internal.messages.Message;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.DB4OUtil.DB4OUtil;
import model.EcoSystem;
import model.Person.Donors;
import model.Person.DonorsDirectory;

/**
 *
 * @author varshareddykumbham
 */
public class DonorRegistrationJPanel extends javax.swing.JPanel {
    List<String> userList = new ArrayList<String>();
    String city;
    DB4OUtil dB4OUtil;
    DonorsDirectory donorDirectory;
    JPanel upContainer;
    String emailAdd;
    EcoSystem ecosystem;
    /**
     * Creates new form DonorRegistrationJPanel
     */
    public DonorRegistrationJPanel(JPanel upContainer, EcoSystem system, DonorsDirectory donorDirectory, DB4OUtil dB4OUtil) {
        initComponents();
        this.upContainer = upContainer;
        tfCity.setText(city);
        this.ecosystem = system;
        this.city = city;
        this.donorDirectory = donorDirectory;
        this.dB4OUtil = dB4OUtil;
        populateUser();
    }
    
    List<String> bloodTypeList = new ArrayList<String>();

    public void populateUser() {
        for (Donors donor : ecosystem.getListOfDonors()) {
            userList.add(donor.getDonorName());
        }
    }
    private boolean checkAge(String age) {
        Pattern pattern = Pattern.compile("[0-9]+");
        Matcher matcher = pattern.matcher(age);
        boolean bool = matcher.matches();
        if (!bool) {
            JOptionPane.showMessageDialog(null, "Age should only be numbers");
            return false;
        } else {
            int age1 = Integer.parseInt(age);
            if (age1 < 0 || age1 > 200) {
                JOptionPane.showMessageDialog(null, "Age should between");
            }
            return true;
        }
    }

    public boolean checkFirstname(String text) {

        if (text.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")) {
            for (String s : userList) {
                if (s.equalsIgnoreCase(text)) {
                    JOptionPane.showMessageDialog(null, "User already exists");
                    return false;
                }
            }

            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Names should contain only alphabets");
            return false;
        }
    }

    private boolean checkPhone(String ph) {
        Pattern pattern = Pattern.compile("[0-9]{10}");
        Matcher matcher = pattern.matcher(ph);
        boolean bool = matcher.matches();
        if (!bool) {
            return true;
        } else {

            return true;
        }
    }

    private boolean checkUsernamePattern(String username) {
        int f = 0;

        Pattern pattern = Pattern.compile("(?!_).*[A-Za-z0-9._]+@[A-Za-z0-9._]+\\.[A-Za-z]{2,4}");
        Matcher matcher = pattern.matcher(username);
        boolean bool = matcher.matches();
        if (!bool) {
            JOptionPane.showMessageDialog(null, "Special characters are not allowed other than _, @");
            return false;
        } else {

            return true;
        }
    }

    boolean checkforunique() {
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        radSexMale = new javax.swing.JRadioButton();
        radSexFemale = new javax.swing.JRadioButton();
        lblBloodGroup = new javax.swing.JLabel();
        cbBloodGroup = new javax.swing.JComboBox();
        lblContact = new javax.swing.JLabel();
        tfContact = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        tfCity = new javax.swing.JTextField();
        lblBloodAvailable = new javax.swing.JLabel();
        radBloodAvailableNowYes = new javax.swing.JRadioButton();
        radBloodAvailableNo = new javax.swing.JRadioButton();
        lblPOCTitle = new javax.swing.JLabel();
        lblPOCName = new javax.swing.JLabel();
        tfPOCName = new javax.swing.JTextField();
        lblPOCContact = new javax.swing.JLabel();
        tfPOCContact = new javax.swing.JTextField();
        btnRegisterDonor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        btnBack.setBackground(new java.awt.Color(0, 183, 210));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 183, 210));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("DONOR REGISTRATION FORM");

        tfName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name:");

        lblAge.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAge.setText("Age:");

        tfAge.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblSex.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSex.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSex.setText("Sex:");

        radSexMale.setBackground(new java.awt.Color(255, 255, 255));
        radSexMale.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radSexMale.setText("Male");
        radSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexMaleActionPerformed(evt);
            }
        });

        radSexFemale.setBackground(new java.awt.Color(255, 255, 255));
        radSexFemale.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radSexFemale.setText("Female");
        radSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexFemaleActionPerformed(evt);
            }
        });

        lblBloodGroup.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblBloodGroup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBloodGroup.setText("Blood Group:");

        cbBloodGroup.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cbBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloodGroupActionPerformed(evt);
            }
        });

        lblContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblContact.setText("Contact Number:");

        tfContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContactActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email-Id:");

        tfEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblAddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddress.setText("Address:");

        tfAddress.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblCity.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCity.setText("City:");

        tfCity.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblBloodAvailable.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblBloodAvailable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBloodAvailable.setText("Is Blood available now:");

        radBloodAvailableNowYes.setBackground(new java.awt.Color(255, 255, 255));
        radBloodAvailableNowYes.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radBloodAvailableNowYes.setText("Yes");
        radBloodAvailableNowYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radOrganAvailableNowYesActionPerformed(evt);
            }
        });

        radBloodAvailableNo.setBackground(new java.awt.Color(255, 255, 255));
        radBloodAvailableNo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        radBloodAvailableNo.setText("No");

        lblPOCTitle.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        lblPOCTitle.setForeground(new java.awt.Color(0, 183, 210));
        lblPOCTitle.setText("Point of contact in emergency:");

        lblPOCName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPOCName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPOCName.setText("Name:");

        tfPOCName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblPOCContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPOCContact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPOCContact.setText("Contact number:");

        tfPOCContact.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tfPOCContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOCContactActionPerformed(evt);
            }
        });

        btnRegisterDonor.setBackground(new java.awt.Color(0, 183, 210));
        btnRegisterDonor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnRegisterDonor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterDonor.setText("Register As A Donor");
        btnRegisterDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDonorActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BloodRequest/bloddRequestNew.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegisterDonor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPOCName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPOCContact))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPOCName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfPOCContact, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(249, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radSexMale, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radSexFemale))
                                    .addComponent(cbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(radBloodAvailableNowYes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radBloodAvailableNo))
                                        .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblBloodAvailable)
                            .addComponent(lblPOCTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(lblTitle))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSex)
                            .addComponent(radSexMale)
                            .addComponent(radSexFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBloodGroup)
                            .addComponent(cbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContact)
                            .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddress)
                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radBloodAvailableNowYes)
                            .addComponent(radBloodAvailableNo))
                        .addGap(18, 18, 18)
                        .addComponent(lblPOCTitle)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPOCName)
                    .addComponent(tfPOCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPOCContact)
                    .addComponent(tfPOCContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnRegisterDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        upContainer.remove(this);
        CardLayout layout = (CardLayout) upContainer.getLayout();
        layout.previous(upContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void radSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSexMaleActionPerformed

    private void radSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSexFemaleActionPerformed

    private void cbBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloodGroupActionPerformed

    private void tfPOCContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOCContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOCContactActionPerformed

    private void btnRegisterDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDonorActionPerformed
        int f = 0;
        String name = tfName.getText();
        //String lastname= txtName1.getText();
        String sex;
        emailAdd = tfEmail.getText();
        if (radSexMale.isSelected()) {
            sex = radSexMale.getText();
        } else {
            sex = radSexFemale.getText();
        }
        String bloodGroup = cbBloodGroup.getSelectedItem().toString();
        String contactNumber = tfContact.getText();
        String address = tfAddress.getText();
        String emergencyPOC = tfPOCName.getText();
        String emergencyPOC_Num = tfPOCContact.getText();
        //int age =Integer.parseInt(txtAge.getText());
        int age = 30;
        boolean isBloodAvaiNow = false;
        if (radBloodAvailableNowYes.isSelected()) {
            isBloodAvaiNow = true;
        } else if (radBloodAvailableNo.isSelected()) {
            isBloodAvaiNow = false;
        }

        if (checkFirstname(name)) {
            f++;
        } else {
            return;
        }
        if (checkAge(tfAge.getText())) {
            age = Integer.parseInt(tfAge.getText());
            f++;
        } else {
            return;
        }
        
        //String contactNumber=(phoneJTextField.getText());
       if(contactNumber == null || contactNumber.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter Contact Number");
                return;
            }
             else{
                 if(!contactNumber.matches("^(?=.*[0-9]).{10,10}")){
                     JOptionPane.showMessageDialog(null, "Please enter valid Contact Number");
                     return;
                 }
             }
        if (checkUsernamePattern(emailAdd)) {
            f++;
        } else {
            return;
        }
        if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "Address cannot be empty");
            return;
        }
          if(emergencyPOC_Num == null || emergencyPOC_Num.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter Contact Number");
                return;
            }
             else{
                 if(!emergencyPOC_Num.matches("^(?=.*[0-9]).{10,10}")){
                     JOptionPane.showMessageDialog(null, "Please enter valid Contact Number");
                     return;
                 }
             }
        if (checkFirstname(emergencyPOC)) {
            f++;
        } else {
            return;
        }

        Donors d = ecosystem.createDonor(name, age, sex, bloodGroup, contactNumber, address, emailAdd, emergencyPOC, emergencyPOC_Num, isBloodAvaiNow, bloodTypeList);
        dB4OUtil.storeSystem(ecosystem);
        JOptionPane.showMessageDialog(null, "Thanks for donation");
        populateUser();

        if (f == 0) {
            JOptionPane.showConfirmDialog(null, "Please enter the right details");

        }
        sendMail(emailAdd);
    }//GEN-LAST:event_btnRegisterDonorActionPerformed

    private void tfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContactActionPerformed

    private void radOrganAvailableNowYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radOrganAvailableNowYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radOrganAvailableNowYesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterDonor;
    private javax.swing.JComboBox cbBloodGroup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBloodAvailable;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPOCContact;
    private javax.swing.JLabel lblPOCName;
    private javax.swing.JLabel lblPOCTitle;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radBloodAvailableNo;
    private javax.swing.JRadioButton radBloodAvailableNowYes;
    private javax.swing.JRadioButton radSexFemale;
    private javax.swing.JRadioButton radSexMale;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfContact;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPOCContact;
    private javax.swing.JTextField tfPOCName;
    // End of variables declaration//GEN-END:variables

    private void sendMail(String toEmail) {
        try
	    {
                final String fromEmail = "blooddonationsystem22@gmail.com"; //requires valid gmail id
		final String password = "ordotzyygwvfjdnj"; // correct password for gmail id
		String subject = "Thanks for the donation";
                String body = "Thank you for saving people lives! Be safe and happy";
		System.out.println("TLSEmail Start");
		Properties props = new Properties();
		props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
		props.put("mail.smtp.port", "587"); //TLS Port
		props.put("mail.smtp.auth", "true"); //enable authentication
		props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS
		
                //create Authenticator object to pass in Session.getInstance argument
		Authenticator auth = new Authenticator() {
			//override the getPasswordAuthentication method
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(fromEmail, password);
			}
		};
		Session session = Session.getInstance(props, auth);
                MimeMessage msg = new MimeMessage(session);
	      //set message headers
	      msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
	      msg.addHeader("format", "flowed");
	      msg.addHeader("Content-Transfer-Encoding", "8bit");

	      msg.setFrom(new InternetAddress("no_reply@example.com", "NoReply-JD"));

	      msg.setReplyTo(InternetAddress.parse("no_reply@example.com", false));

	      msg.setSubject(subject, "UTF-8");

	      msg.setText(body, "UTF-8");

	      msg.setSentDate(new Date());
              msg.setRecipients(javax.mail.Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
	      System.out.println("Message is ready");
    	  Transport.send(msg);  

	      System.out.println("EMail Sent Successfully!!");
              JOptionPane.showMessageDialog(null, "EMail Sent Successfully!!");
	    }
	catch (Exception e) {
	    e.printStackTrace();
	}
    }
}
