/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Network.Network;

/**
 *
 * @author sahithigaddam
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    JPanel usersPanel;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    Network network;
    public AdminJPanel(JPanel usersPanel, Enterprise enterprise,EcoSystem ecoSystem,Network network) {
        initComponents();
        this.usersPanel = usersPanel;
        this.enterprise = enterprise;
        this.ecoSystem=ecoSystem;
        this.network=network;
        System.out.println(enterprise.getOrganizationName().concat("hospital"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfAdminDashboard = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();
        btnOrganizations = new javax.swing.JButton();
        btnEmployees = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        tfAdminDashboard.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        tfAdminDashboard.setForeground(new java.awt.Color(0, 183, 210));
        tfAdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfAdminDashboard.setText("ADMIN DASHBOARD");

        btnUsers.setBackground(new java.awt.Color(0, 183, 210));
        btnUsers.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setText(" Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnOrganizations.setBackground(new java.awt.Color(0, 183, 210));
        btnOrganizations.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnOrganizations.setForeground(new java.awt.Color(255, 255, 255));
        btnOrganizations.setText("  Organization");
        btnOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationsActionPerformed(evt);
            }
        });

        btnEmployees.setBackground(new java.awt.Color(0, 183, 210));
        btnEmployees.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnEmployees.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployees.setText("Employees");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Admin/EmployeeAdminJPanel.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Admin/UserAccountAdminJPanel.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Admin/OrganizationAdminJPanel (4).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel4)
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(btnOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(797, 797, 797))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(tfAdminDashboard)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrganizations)
                    .addComponent(btnEmployees)
                    .addComponent(btnUsers))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        UsersJPanel manageusers = new UsersJPanel(usersPanel, enterprise);
        usersPanel.add("ManageUserAccountJPanel", manageusers);
        CardLayout layout = (CardLayout) usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationsActionPerformed
        OrganizationsJPanel manageorganization = new OrganizationsJPanel(usersPanel, enterprise.getLisOfOrganizations(),enterprise);
        usersPanel.add("manageOrganizationJPanel", manageorganization);
        CardLayout layout = (CardLayout) usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnOrganizationsActionPerformed

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed

        EmployeesJPanel manageemployees = new EmployeesJPanel(usersPanel, enterprise.getLisOfOrganizations(),enterprise,ecoSystem);
        usersPanel.add("manageOrganizationJPanel", manageemployees);
        CardLayout layout = (CardLayout) usersPanel.getLayout();
        layout.next(usersPanel);
    }//GEN-LAST:event_btnEmployeesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnOrganizations;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel tfAdminDashboard;
    // End of variables declaration//GEN-END:variables
}
