/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.Employee.Employee;
import model.Enterprise.Enterprise;
import model.Organization.Organization;
import model.Organization.OrganizationDirectory;

/**
 *
 * @author varshareddykumbham
 */
public class EmployeesJPanel extends javax.swing.JPanel {
    private OrganizationDirectory organizationDirectory;
    private JPanel userProcessContainer;
    ArrayList<String> userList = new ArrayList<String>();
    EcoSystem ecoSystem;
    /**
     * Creates new form EmployeesJPanel
     */
    public EmployeesJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDirectory,Enterprise enterprise,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        this.ecoSystem=ecoSystem;
        loadInitialEmmployeeTable();
        loadOrganizationEmployeeCombobox();
    }
    
    public void loadOrganizationEmployeeCombobox(){
        cbOrganization.removeAllItems();
        cbOrganization.addItem("--Select--");
        for (Organization organization : organizationDirectory.getOrganizationList()){
            cbOrganization.addItem(organization);
        }
    }

    private void loadInitialEmmployeeTable(){
        DefaultTableModel model = (DefaultTableModel) tblCurrentEmployeeList.getModel();
        
        model.setRowCount(0);

        for(Organization or:organizationDirectory.getOrganizationList()){
            for (Employee employee : or.getListOfEmployees().getListOfEmployees()){
                Object[] row = new Object[2];
                row[0] = employee.getEmployeeId();
                row[1] = employee.getEmployeeName();
                userList.add(employee.getEmployeeName());
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurrentEmployeeList = new javax.swing.JTable();
        btnCreateNewEmployee = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        tfNameVal = new javax.swing.JTextField();
        cbOrganization = new javax.swing.JComboBox();
        lbOrganizationName = new javax.swing.JLabel();
        tfCreateNewEmployeeHeading = new javax.swing.JLabel();
        lblCurrentEmployeesHead = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        tblCurrentEmployeeList.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblCurrentEmployeeList.setForeground(new java.awt.Color(153, 51, 0));
        tblCurrentEmployeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCurrentEmployeeList.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblCurrentEmployeeList.setSelectionForeground(new java.awt.Color(255, 255, 51));
        jScrollPane1.setViewportView(tblCurrentEmployeeList);

        btnCreateNewEmployee.setBackground(new java.awt.Color(0, 183, 210));
        btnCreateNewEmployee.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnCreateNewEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewEmployee.setText("Create");
        btnCreateNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewEmployeeActionPerformed(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(0, 183, 210));
        btnGoBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Employee Name:");

        tfNameVal.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tfNameVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameValActionPerformed(evt);
            }
        });

        cbOrganization.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrganizationActionPerformed(evt);
            }
        });

        lbOrganizationName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lbOrganizationName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbOrganizationName.setText("Organization:");

        tfCreateNewEmployeeHeading.setBackground(new java.awt.Color(255, 255, 255));
        tfCreateNewEmployeeHeading.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        tfCreateNewEmployeeHeading.setForeground(new java.awt.Color(0, 183, 210));
        tfCreateNewEmployeeHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfCreateNewEmployeeHeading.setText("CREATE EMPLOYEE");

        lblCurrentEmployeesHead.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblCurrentEmployeesHead.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCurrentEmployeesHead.setText("Existing Employees");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Employee/createEmployee.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tfNameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(lbOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurrentEmployeesHead)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnCreateNewEmployee)))
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(585, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tfCreateNewEmployeeHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1065, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOrganizationName)
                            .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(tfNameVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnCreateNewEmployee)
                        .addGap(56, 56, 56)
                        .addComponent(lblCurrentEmployeesHead)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCreateNewEmployeeHeading))
                    .addContainerGap(527, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewEmployeeActionPerformed
        boolean check;
        check=cbOrganization.getSelectedIndex()>0;
        if(!check){
            JOptionPane.showMessageDialog(null, "No organization is selected, please select an organisation");
            return;
        }

        Organization organization = (Organization) cbOrganization.getSelectedItem();
        String name = tfNameVal.getText();
        for(String s:userList){
            if(s.equals(name)){
                JOptionPane.showMessageDialog(null, "Employee name already exists, please try again");
                return;
            }
        }

        if(name.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")){
            organization.getListOfEmployees().createEmployee(ecoSystem.getEmployeeId(),name);
            ecoSystem.incrementEmployeeId();
            loadInitialEmmployeeTable();
            tfNameVal.setText("");}
        else{
            JOptionPane.showMessageDialog(null, "Try again, names can't contain numbers or special characters");
        }

    }//GEN-LAST:event_btnCreateNewEmployeeActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void tfNameValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameValActionPerformed

    private void cbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewEmployee;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JComboBox cbOrganization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbOrganizationName;
    private javax.swing.JLabel lblCurrentEmployeesHead;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblCurrentEmployeeList;
    private javax.swing.JLabel tfCreateNewEmployeeHeading;
    private javax.swing.JTextField tfNameVal;
    // End of variables declaration//GEN-END:variables
}
