/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Admin;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Enterprise.BloodBankEnterprise;
import model.Enterprise.Enterprise;
import model.Enterprise.FederalGovernmentEnterprise;
import model.Enterprise.HospitalEnterprise;
import model.Enterprise.RehabEnterprise;
import model.Organization.Organization;
import model.Organization.Organization.OrganizationType;
import model.Organization.OrganizationDirectory;

/**
 *
 * @author varshareddykumbham
 */
public class OrganizationsJPanel extends javax.swing.JPanel {
    private OrganizationDirectory organizationDirectory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form OrganizationsJPanel
     */
    
    public OrganizationsJPanel(JPanel userProcessContainer,OrganizationDirectory directory,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = directory;
        this.enterprise= enterprise;
        
        initTable();
        initComboBox();
    }
    
    private void initComboBox(){
        cbOrganizationType.removeAllItems();
        cbOrganizationType.addItem("--Select--");
        System.out.println("Enterprise");
        System.out.println(enterprise);
        for (OrganizationType type : Organization.OrganizationType.values()){
               System.out.print(type.toString());
             if(enterprise instanceof HospitalEnterprise){
                 if(type.toString().equals("MedicalCare") || type.toString().equals("MedicalDiagnostics")){
                 cbOrganizationType.addItem(type);}
             }
             if(enterprise instanceof BloodBankEnterprise){
                 if(type.toString().equals("MedicalFacilities")){
                 cbOrganizationType.addItem(type);}
                 
             }
             if(enterprise instanceof FederalGovernmentEnterprise){
                 if(type.toString().equals("PoliciesFinance")|| type.toString().equals("MedicalAwarnessCampaign")){
                 cbOrganizationType.addItem(type);}
                 
             }
             if(enterprise instanceof RehabEnterprise){
                 if(type.toString().equals("Physician")){
                 cbOrganizationType.addItem(type);}
                 
             }
                
            
        }
    }

    private void initTable(){
        DefaultTableModel model = (DefaultTableModel) tblCurrentOrganizations.getModel();
        model.setRowCount(0);
        for (Organization organization : organizationDirectory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationName();
            row[1]= organization.getOrganizationType().getValue();
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblOrganization = new javax.swing.JScrollPane();
        tblCurrentOrganizations = new javax.swing.JTable();
        btnCreateOrganization = new javax.swing.JButton();
        cbOrganizationType = new javax.swing.JComboBox();
        lblOrganizationType = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCreateOrganization = new javax.swing.JLabel();
        lblPresentOrganization = new javax.swing.JLabel();
        lblOrganizationName = new javax.swing.JLabel();
        tfOrganizationName = new javax.swing.JTextField();

        tblCurrentOrganizations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCurrentOrganizations.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblCurrentOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organisation Name", "Organisation Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrganization.setViewportView(tblCurrentOrganizations);

        btnCreateOrganization.setBackground(new java.awt.Color(255, 0, 51));
        btnCreateOrganization.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnCreateOrganization.setText("Add Organization");
        btnCreateOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrganizationActionPerformed(evt);
            }
        });

        cbOrganizationType.setBackground(new java.awt.Color(255, 0, 51));
        cbOrganizationType.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cbOrganizationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrganizationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrganizationTypeActionPerformed(evt);
            }
        });

        lblOrganizationType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOrganizationType.setForeground(new java.awt.Color(255, 0, 51));
        lblOrganizationType.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrganizationType.setText("Organization Type :");

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCreateOrganization.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblCreateOrganization.setForeground(new java.awt.Color(255, 0, 51));
        lblCreateOrganization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateOrganization.setText("CREATE ORGANIZATION");

        lblPresentOrganization.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPresentOrganization.setForeground(new java.awt.Color(255, 0, 51));
        lblPresentOrganization.setText("Current Organizations");

        lblOrganizationName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOrganizationName.setForeground(new java.awt.Color(255, 0, 51));
        lblOrganizationName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOrganizationName.setText("Organization Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCreateOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbOrganizationType, 0, 234, Short.MAX_VALUE)
                                        .addComponent(tfOrganizationName)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(btnCreateOrganization))))
                                .addComponent(lblPresentOrganization)
                                .addComponent(tblOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(638, 638, 638)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCreateOrganization)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrganizationType))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrganizationName)
                        .addComponent(tfOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(btnCreateOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblPresentOrganization)
                    .addGap(18, 18, 18)
                    .addComponent(tblOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrganizationActionPerformed

        boolean selected;
        selected=cbOrganizationType.getSelectedIndex()>0;
        if(!selected){
            JOptionPane.showMessageDialog(null, "Select an Organisation");
        }

        OrganizationType type = (OrganizationType) cbOrganizationType.getSelectedItem();
        organizationDirectory.createOrganization(type,tfOrganizationName.getText());
        tfOrganizationName.setText("");
        initTable();
    }//GEN-LAST:event_btnCreateOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbOrganizationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrganizationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrganizationTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateOrganization;
    private javax.swing.JComboBox cbOrganizationType;
    private javax.swing.JLabel lblCreateOrganization;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JLabel lblPresentOrganization;
    private javax.swing.JTable tblCurrentOrganizations;
    private javax.swing.JScrollPane tblOrganization;
    private javax.swing.JTextField tfOrganizationName;
    // End of variables declaration//GEN-END:variables
}
