/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.Network.Network;

/**
 *
 * @author sahithigaddam
 */
public class EnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseJPanel
     */
    private JPanel usersPanel;
    private EcoSystem system;
    ArrayList<String> entnet = new ArrayList<String>();
    public EnterpriseJPanel(JPanel usersPanel, EcoSystem system) {
        initComponents();
        this.usersPanel = usersPanel;
        this.system = system;
        loadEnterpriseTable();
        LoadComboBox();
        loadtable();
    }
    
    private void loadEnterpriseTable() {
        DefaultTableModel entTable = (DefaultTableModel) tbl_list_of_enterprises.getModel();
        entTable.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getListOfEnterprises().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getOrganizationName();
                row[1] = network.getName();
                row[2] = enterprise.getenterpriseType().getType();
                entTable.addRow(row);
            }
        }
    }

    private boolean checkcurrentEnterprise(Enterprise.EnterpriseType type) {
        ArrayList<Enterprise.EnterpriseType> estEnterprises = new ArrayList<Enterprise.EnterpriseType>();
        for (Network network : system.getNetworkList()) {
            if (network == cbCityName.getSelectedItem()) {
                for (Enterprise enterprise : network.getListOfEnterprises().getEnterpriseList()) {
                    estEnterprises.add(enterprise.getenterpriseType());
                }

            }
        }
        if (estEnterprises.contains(type)&&(type.getType().equalsIgnoreCase("Federal Government")||type.getType().equalsIgnoreCase("Blood Bank"))) {
            JOptionPane.showMessageDialog(null, "One enterprise allowed for the selected option");
            return true;
        }

        return false;
    }

    private void LoadComboBox() {
        cbCityName.removeAllItems();
        cbEnterpriseType.removeAllItems();
        cbCityName.addItem("--Select--");
        cbEnterpriseType.addItem("--Select--");
        cbCurrentEnterprise.addItem("-All Enterprises-");
        for (Network network : system.getNetworkList()) {
            cbCityName.addItem(network);
            cbCurrentEnterprise.addItem(network.toString());
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            cbEnterpriseType.addItem(type);
        }

    }
    
    public void loadtable(){
        DefaultTableModel model = (DefaultTableModel) tbl_list_of_enterprises.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
                for (Enterprise enterprise : network.getListOfEnterprises().getEnterpriseList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getOrganizationName();
                    row[1] = network.getName();
                    row[2] = enterprise.getenterpriseType().getType();
                    model.addRow(row);
                }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_list_of_enterprises = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbCityName = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfEnterpriseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEnterpriseType = new javax.swing.JComboBox();
        btnAddNewEnterprise = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbCurrentEnterprise = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        tbl_list_of_enterprises.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_list_of_enterprises.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tbl_list_of_enterprises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_list_of_enterprises);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("City Name:");

        cbCityName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cbCityName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCityNameActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Enterprise Name:");

        tfEnterpriseName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Type of Enterprise:");

        cbEnterpriseType.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cbEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterpriseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterpriseTypeActionPerformed(evt);
            }
        });

        btnAddNewEnterprise.setBackground(new java.awt.Color(0, 183, 210));
        btnAddNewEnterprise.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAddNewEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewEnterprise.setText("Add");
        btnAddNewEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEnterpriseActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 183, 210));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 183, 210));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTERPRISES");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 183, 210));
        jLabel7.setText("Current enterprises");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 183, 210));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Add Enterprise");

        cbCurrentEnterprise.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbCurrentEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCurrentEnterpriseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfEnterpriseName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbEnterpriseType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddNewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbCurrentEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(311, 311, 311))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbCurrentEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddNewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCityNameActionPerformed

    private void cbEnterpriseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterpriseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEnterpriseTypeActionPerformed

    private void btnAddNewEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEnterpriseActionPerformed

        int counter = 0;
        String name = tfEnterpriseName.getText();
        String city = cbCityName.getSelectedItem().toString();
        if (name.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")) {
            name = name.trim();
            for (String s : entnet) {
                if (s.equalsIgnoreCase(name + city)) {
                    JOptionPane.showMessageDialog(null, "Please try aagain, The Enterprise already exists in this city");
                    counter++;
                    break;
                }
            }
            if (counter == 0) {
                entnet.add(name + city);
                Network network = (Network) cbCityName.getSelectedItem();
                Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) cbEnterpriseType.getSelectedItem();

                if (network == null || type == null) {
                    JOptionPane.showMessageDialog(null, "Please try again, Invalid Input!");
                    return;
                }

                if (checkcurrentEnterprise(type)) {
                    return;

                } else {
                    Enterprise enterprise = network.getListOfEnterprises().createAndAddEnterprise(name, type);

                    loadEnterpriseTable();
                    tfEnterpriseName.setText("");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Invalid input, Enterprise can only contain alphabets");
        }
    }//GEN-LAST:event_btnAddNewEnterpriseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        usersPanel.remove(this);
        Component[] componentArray = usersPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminJPanel sysAdminJPanel = (SystemAdminJPanel) component;
        sysAdminJPanel.populateTree();

        CardLayout layout = (CardLayout) usersPanel.getLayout();
        layout.previous(usersPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbCurrentEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCurrentEnterpriseActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_list_of_enterprises.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            if (network.getName() == cbCurrentEnterprise.getSelectedItem()) {
                for (Enterprise enterprise : network.getListOfEnterprises().getEnterpriseList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getOrganizationName();
                    row[1] = network.getName();
                    row[2] = enterprise.getenterpriseType().getType();
                    model.addRow(row);
                }
            }else if(cbCurrentEnterprise.getSelectedIndex()==0){
                loadtable();
            }
        }
    }//GEN-LAST:event_cbCurrentEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEnterprise;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cbCityName;
    private javax.swing.JComboBox<String> cbCurrentEnterprise;
    private javax.swing.JComboBox cbEnterpriseType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_list_of_enterprises;
    private javax.swing.JTextField tfEnterpriseName;
    // End of variables declaration//GEN-END:variables
}
