/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdmin;

import model.EcoSystem;
import model.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sindhurabandaru
 */
public class NetworkJPanel extends javax.swing.JPanel {
    
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    ArrayList<String> networkString = new ArrayList<String>();

    /**
     * Creates new form NetworkJPanel
     */
    public NetworkJPanel() {
        initComponents();
    }
    
    /**
     *
     * Creates new form ManageNetworkJPanel
     */
    public NetworkJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        addanewnetworks();
        LoadNetworkTable();
    }
    public void addanewnetworks(){
        for(Network n:ecoSystem.getNetworkList()){
            networkString.add(n.toString());
        }
    }

    private void LoadNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tbllistOfNetworks.getModel();
        //set the row count as zero on initial page load
        model.setRowCount(0);
        for (Network network : ecoSystem.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbllistOfNetworks = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblNetworkOfCities = new javax.swing.JLabel();
        lblCitiesPresentInNetwork = new javax.swing.JLabel();
        lblCityToNetwork = new javax.swing.JLabel();
        btnAddCity = new javax.swing.JButton();
        tfCityName = new javax.swing.JTextField();
        lblCityName = new javax.swing.JLabel();

        tbllistOfNetworks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbllistOfNetworks.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tbllistOfNetworks.setForeground(new java.awt.Color(255, 0, 51));
        tbllistOfNetworks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbllistOfNetworks.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbllistOfNetworks.setSelectionForeground(new java.awt.Color(255, 255, 51));
        jScrollPane1.setViewportView(tbllistOfNetworks);

        btnBack.setBackground(new java.awt.Color(0, 183, 210));
        btnBack.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblNetworkOfCities.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblNetworkOfCities.setForeground(new java.awt.Color(0, 183, 210));
        lblNetworkOfCities.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNetworkOfCities.setText("Network of Cities");

        lblCitiesPresentInNetwork.setBackground(new java.awt.Color(255, 255, 255));
        lblCitiesPresentInNetwork.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        lblCitiesPresentInNetwork.setForeground(new java.awt.Color(0, 183, 210));
        lblCitiesPresentInNetwork.setText("Cities present in network");

        lblCityToNetwork.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblCityToNetwork.setForeground(new java.awt.Color(0, 183, 210));
        lblCityToNetwork.setText("Add a city to the network");

        btnAddCity.setBackground(new java.awt.Color(0, 183, 210));
        btnAddCity.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAddCity.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCity.setText("Add City");
        btnAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCityActionPerformed(evt);
            }
        });

        tfCityName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lblCityName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblCityName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCityName.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(lblNetworkOfCities, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCityToNetwork)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddCity))))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCitiesPresentInNetwork)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNetworkOfCities))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCityToNetwork)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCityName)
                            .addComponent(tfCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCitiesPresentInNetwork)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] ArrayofComponent = userProcessContainer.getComponents();
        Component component = ArrayofComponent[ArrayofComponent.length - 1];
        SystemAdminJPanel sysAdminwJPanel = (SystemAdminJPanel) component;
        sysAdminwJPanel.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCityActionPerformed

        int Flag=0;
        String name = tfCityName.getText();
        if (name.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")) {
            name = name.trim();
            for(String s:networkString){
                if(s.equalsIgnoreCase(name)){
                    JOptionPane.showMessageDialog(null, "Please add another city, the city already exists in the network");
                    Flag=1;
                    break;
                }
            }
            if(Flag==0){
                networkString.add(name);
                Network network = ecoSystem.createAndAddNetwork();
                network.setName(name);
                LoadNetworkTable();
                tfCityName.setText("");
            }
        } else {
            //Throw a dialog box if a special character is used
            JOptionPane.showMessageDialog(null,"Invalid text, special chanracters not allowed");
        }
    }//GEN-LAST:event_btnAddCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCitiesPresentInNetwork;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCityToNetwork;
    private javax.swing.JLabel lblNetworkOfCities;
    private javax.swing.JTable tbllistOfNetworks;
    private javax.swing.JTextField tfCityName;
    // End of variables declaration//GEN-END:variables
}
